port-file: "/tmp/portfile"
requests:
  - torrent:
      credentials:
        username: "admin"
        password: "password"
      requests:
        - method: "POST"
          url: "http://localhost:8080/api/v2/auth/login"
          payload: "username={{.Username}}&password={{.Password}}"
          content-type: "application/x-www-form-urlencoded"
        - method: "POST"
          url: "http://localhost:8080/api/v2/app/setPreferences"
          payload: "json={\"listen_port\": \"{{.Port}}\"}"
          content-type: "application/x-www-form-urlencoded"
